name: conversor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  feather_icons_flutter: ^4.7.4
  json_annotation: ^2.4.0
  http: ^0.12.0+2
  intl: ^0.16.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true